name: hyperparam_example
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.20.0
  - pandas=1.2.1
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - pip
  - pip:
    - tensorflow>=2.4.0rc0
    - mlflow>=1.0
    - Gpy==1.9.9
    - GpyOpt==1.2.6
    - pyDOE==0.3.8
    - hyperopt==0.2.5

